name: "Review flow"
description: "Automates review flow action"
author: "kingdaro"
inputs:
  token:
    description: "github token"
    default: ${{ secrets.GITHUB_TOKEN }}
runs:
  using: "node12"
  main: "src/index.js"
