name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn && yarn ci
